package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.09 09:13:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoituskertaTest {



  // Generated by ComTest BEGIN
  /** testGetPvm156 */
  @Test
  public void testGetPvm156() {    // Harjoituskerta: 156
    Harjoituskerta juoksu1 = new Harjoituskerta(); 
    juoksu1.vastaaJuoksu(); 
    { String _l_=juoksu1.getPvm(),_r_="7.12.20"; if ( !_l_.matches(_r_) ) fail("From: Harjoituskerta line: 159" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKesto180 */
  @Test
  public void testGetKesto180() {    // Harjoituskerta: 180
    Harjoituskerta juoksu1 = new Harjoituskerta(); 
    juoksu1.vastaaJuoksu(); 
    { String _l_=juoksu1.getKesto(),_r_="44:32"; if ( !_l_.matches(_r_) ) fail("From: Harjoituskerta line: 183" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMatka195 */
  @Test
  public void testGetMatka195() {    // Harjoituskerta: 195
    Harjoituskerta juoksu1 = new Harjoituskerta(); 
    juoksu1.vastaaJuoksu(); 
    { String _l_=juoksu1.getMatka(),_r_="7.0"; if ( !_l_.matches(_r_) ) fail("From: Harjoituskerta line: 198" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKuormittavuus210 */
  @Test
  public void testGetKuormittavuus210() {    // Harjoituskerta: 210
    Harjoituskerta juoksu1 = new Harjoituskerta(); 
    juoksu1.vastaaJuoksu(); 
    { String _l_=juoksu1.getKuormittavuus(),_r_="6"; if ( !_l_.matches(_r_) ) fail("From: Harjoituskerta line: 213" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKommentti225 */
  @Test
  public void testGetKommentti225() {    // Harjoituskerta: 225
    Harjoituskerta juoksu1 = new Harjoituskerta(); 
    juoksu1.vastaaJuoksu(); 
    { String _l_=juoksu1.getKommentti(),_r_="Jaksoin juosta todella hyvin"; if ( !_l_.matches(_r_) ) fail("From: Harjoituskerta line: 228" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString238 */
  @Test
  public void testToString238() {    // Harjoituskerta: 238
    Harjoituskerta har = new Harjoituskerta(); 
    har.rekisteroi(); 
    har.vastaaJuoksu(); 
    assertEquals("From: Harjoituskerta line: 242", "1|7.12.20|1|44:32|7.0|6|Jaksoin juosta todella hyvin", har.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse257 */
  @Test
  public void testParse257() {    // Harjoituskerta: 257
    Harjoituskerta har = new Harjoituskerta(); 
    har.parse("   1  |  7.12.20  |   1  | 44:32 | 7.0 | 6 |Jaksoin juosta todella hyvin  "); 
    assertEquals("From: Harjoituskerta line: 260", 1, har.getLajiNro()); 
    assertEquals("From: Harjoituskerta line: 261", "1|7.12.20|1|44:32|7.0|6|Jaksoin juosta todella hyvin", har.toString()); 
    har.rekisteroi(); 
    int n = har.getTunnusNro(); 
    har.parse(""+(n+20)); 
    har.rekisteroi(); 
    assertEquals("From: Harjoituskerta line: 267", n+20+1, har.getTunnusNro()); 
    assertEquals("From: Harjoituskerta line: 268", "" + (n+20+1) + "|7.12.20|1|44:32|7.0|6|Jaksoin juosta todella hyvin", har.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi321 */
  @Test
  public void testRekisteroi321() {    // Harjoituskerta: 321
    Harjoituskerta juoksu1 = new Harjoituskerta(); 
    assertEquals("From: Harjoituskerta line: 323", 0, juoksu1.getTunnusNro()); 
    juoksu1.rekisteroi(); 
    Harjoituskerta juoksu2 = new Harjoituskerta(); 
    juoksu2.rekisteroi(); 
    int n1 = juoksu1.getTunnusNro(); 
    int n2 = juoksu2.getTunnusNro(); 
    assertEquals("From: Harjoituskerta line: 329", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone343 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone343() throws CloneNotSupportedException {    // Harjoituskerta: 343
    Harjoituskerta har = new Harjoituskerta(); 
    har.parse("   1  |  7.12.20  |   1  | 44:32 | 7.0 | 6 |Jaksoin juosta todella hyvin  "); 
    Harjoituskerta kopio = har.clone(); 
    assertEquals("From: Harjoituskerta line: 348", har.toString(), kopio.toString()); 
    har.parse(" 2  |  9.12.20  |   2 | 45:21 | 5.0 | 7 | Ihan OK meni "); 
    assertEquals("From: Harjoituskerta line: 350", false, kopio.toString().equals(har.toString())); 
  } // Generated by ComTest END
}