package treenipaivakirja.test;
// Generated by ComTest BEGIN
import treenipaivakirja.*;
import java.io.File;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.09 16:22:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LajitTest {



  // Generated by ComTest BEGIN
  /** testLisaa79 */
  @Test
  public void testLisaa79() {    // Lajit: 79
    Lajit lajit = new Lajit(); 
    Laji juoksu1 = new Laji(), juoksu2 = new Laji(); 
    assertEquals("From: Lajit line: 82", 0, lajit.getLkm()); 
    lajit.lisaa(juoksu1); assertEquals("From: Lajit line: 83", 1, lajit.getLkm()); 
    lajit.lisaa(juoksu2); assertEquals("From: Lajit line: 84", 2, lajit.getLkm()); 
    lajit.lisaa(juoksu1); assertEquals("From: Lajit line: 85", 3, lajit.getLkm()); 
    assertEquals("From: Lajit line: 86", juoksu1, lajit.anna(0)); 
    assertEquals("From: Lajit line: 87", juoksu2, lajit.anna(1)); 
    assertEquals("From: Lajit line: 88", juoksu1, lajit.anna(2)); 
    assertEquals("From: Lajit line: 89", false, lajit.anna(1) == juoksu1); 
    assertEquals("From: Lajit line: 90", true, lajit.anna(1) == juoksu2); 
    lajit.lisaa(juoksu1); assertEquals("From: Lajit line: 91", 4, lajit.getLkm()); 
    lajit.lisaa(juoksu1); assertEquals("From: Lajit line: 92", 5, lajit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaaLaji107 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaaLaji107() throws SailoException,CloneNotSupportedException {    // Lajit: 107
    Lajit lajit = new Lajit(); 
    Laji l1 = new Laji(), l2 = new Laji(); 
    l1.rekisteroi(); l2.rekisteroi(); 
    assertEquals("From: Lajit line: 113", 0, lajit.getLkm()); 
    lajit.korvaaTaiLisaaLaji(l1); assertEquals("From: Lajit line: 114", 1, lajit.getLkm()); 
    lajit.korvaaTaiLisaaLaji(l2); assertEquals("From: Lajit line: 115", 2, lajit.getLkm()); 
    Laji l3 = l1.clone(); 
    Iterator<Laji> it = lajit.iterator(); 
    assertEquals("From: Lajit line: 118", true, it.next() == l1); 
    lajit.korvaaTaiLisaaLaji(l3); assertEquals("From: Lajit line: 119", 2, lajit.getLkm()); 
    it = lajit.iterator(); 
    Laji l0 = it.next(); 
    assertEquals("From: Lajit line: 122", l3, l0); 
    assertEquals("From: Lajit line: 123", true, l0 == l3); 
    assertEquals("From: Lajit line: 124", false, l0 == l1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta145 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta145() throws SailoException {    // Lajit: 145
    Lajit lajit = new Lajit(); 
    Laji juoksu1 = new Laji(), juoksu2 = new Laji(); 
    juoksu1.vastaaJuoksu(); 
    juoksu2.vastaaJuoksu(); 
    String hakemisto = "testitreenit"; 
    File ftied = new File(hakemisto+"/lajit.dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    lajit.lueTiedostosta(hakemisto); 
    fail("Lajit: 157 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    lajit.lisaa(juoksu1); 
    lajit.lisaa(juoksu2); 
    lajit.tallenna(hakemisto); 
    lajit = new Lajit();  // Poistetaan vanhat luomalla uusi
    lajit.lueTiedostosta(hakemisto);  // johon ladataan tiedot tiedostosta.
    Iterator<Laji> i = lajit.iterator(); 
    assertEquals("From: Lajit line: 164", true, i.hasNext()); 
    lajit.lisaa(juoksu2); 
    lajit.tallenna(hakemisto); 
    assertEquals("From: Lajit line: 167", true, ftied.delete()); 
    File fbak = new File(hakemisto+"/lajit.bak"); 
    assertEquals("From: Lajit line: 169", true, fbak.delete()); 
    assertEquals("From: Lajit line: 170", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista255 
   * @throws SailoException when error
   */
  @Test
  public void testPoista255() throws SailoException {    // Lajit: 255
    Lajit lajit = new Lajit(); 
    Laji juoksu11 = new Laji(); juoksu11.vastaaJuoksu(); 
    Laji juoksu12 = new Laji(); juoksu12.vastaaJuoksu(); 
    Laji juoksu21 = new Laji(); juoksu21.vastaaJuoksu(); 
    Laji juoksu22 = new Laji(); juoksu22.vastaaJuoksu(); 
    Laji juoksu23 = new Laji(); juoksu23.vastaaJuoksu(); 
    lajit.lisaa(juoksu11); 
    lajit.lisaa(juoksu12); 
    lajit.lisaa(juoksu21); 
    lajit.lisaa(juoksu22); 
    assertEquals("From: Lajit line: 268", false, lajit.poista(juoksu23)); assertEquals("From: Lajit line: 268", 4, lajit.getLkm()); 
    assertEquals("From: Lajit line: 269", true, lajit.poista(juoksu11)); assertEquals("From: Lajit line: 269", 3, lajit.getLkm()); 
    assertEquals("From: Lajit line: 270", juoksu12, lajit.anna(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLajitIterator320 
   * @throws SailoException when error
   */
  @Test
  public void testLajitIterator320() throws SailoException {    // Lajit: 320
    Lajit lajit = new Lajit(); 
    Laji laji1 = new Laji(), laji2 = new Laji(); 
    laji1.rekisteroi(); laji2.rekisteroi(); 
    lajit.lisaa(laji1); 
    lajit.lisaa(laji2); 
    lajit.lisaa(laji1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Laji laji:lajit) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+laji.getTunnusNro()); 
    String tulos = " " + laji1.getTunnusNro() + " " + laji2.getTunnusNro() + " " + laji1.getTunnusNro(); 
    assertEquals("From: Lajit line: 339", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Laji>  i=lajit.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Laji laji = i.next(); 
    ids.append(" "+laji.getTunnusNro()); 
    }
    assertEquals("From: Lajit line: 347", tulos, ids.toString()); 
    Iterator<Laji>  i=lajit.iterator(); 
    assertEquals("From: Lajit line: 350", true, i.next() == laji1); 
    assertEquals("From: Lajit line: 351", true, i.next() == laji2); 
    assertEquals("From: Lajit line: 352", true, i.next() == laji1); 
    try {
    i.next(); 
    fail("Lajit: 354 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi414 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi414() throws SailoException {    // Lajit: 414
    Lajit lajit = new Lajit(); 
    Laji laji1 = new Laji(); laji1.parse("1|juoksu"); 
    Laji laji2 = new Laji(); laji2.parse("2|tennis"); 
    Laji laji3 = new Laji(); laji3.parse("3|kävely"); 
    Laji laji4 = new Laji(); laji4.parse("4|kuntosali"); 
    Laji laji5 = new Laji(); laji5.parse("5|tennis"); 
    lajit.lisaa(laji1); lajit.lisaa(laji2); lajit.lisaa(laji3); lajit.lisaa(laji4); lajit.lisaa(laji5); 
  } // Generated by ComTest END
}