package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.09 14:54:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LajiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi97 */
  @Test
  public void testRekisteroi97() {    // Laji: 97
    Laji juoksu = new Laji(); 
    assertEquals("From: Laji line: 99", 0, juoksu.getTunnusNro()); 
    juoksu.rekisteroi(); 
    Laji juoksu2 = new Laji(); 
    juoksu2.rekisteroi(); 
    int n1 = juoksu.getTunnusNro(); 
    int n2 = juoksu2.getTunnusNro(); 
    assertEquals("From: Laji line: 105", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString117 */
  @Test
  public void testToString117() {    // Laji: 117
    Laji l = new Laji(); 
    l.rekisteroi(); 
    l.vastaaJuoksu(); 
    assertEquals("From: Laji line: 121", "1|juoksu", l.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse136 */
  @Test
  public void testParse136() {    // Laji: 136
    Laji laji = new Laji(); 
    laji.parse("2  |  juoksu"); 
    assertEquals("From: Laji line: 139", 2, laji.getTunnusNro()); 
    assertEquals("From: Laji line: 140", true, laji.toString().startsWith("2|juoksu")); 
    laji.rekisteroi(); 
    int n = laji.getTunnusNro(); 
    laji.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    laji.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Laji line: 145", n+20+1, laji.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone159 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone159() throws CloneNotSupportedException {    // Laji: 159
    Laji laji = new Laji(); 
    laji.parse("   1  | juoksu "); 
    Laji kopio = laji.clone(); 
    assertEquals("From: Laji line: 164", laji.toString(), kopio.toString()); 
    laji.parse(" 2  |  tennis"); 
    assertEquals("From: Laji line: 166", false, kopio.toString().equals(laji.toString())); 
  } // Generated by ComTest END
}