package treenipaivakirja.test;
// Generated by ComTest BEGIN
import treenipaivakirja.SailoException;
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.12 09:59:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreenipaivakirjaTest {


  // Generated by ComTest BEGIN  // Treenipaivakirja: 15
   private Treenipaivakirja treeni; 
   private Harjoituskerta har1; 
   private Harjoituskerta har2; 
   private Laji l11; 
   private Laji l12; 
   private Laji l21; 
   private Laji l22; 
   private Laji l23; 

   public void alustaTreenipaivakirja() {
   treeni = new Treenipaivakirja(); 
   har1 = new Harjoituskerta(); har1.vastaaJuoksu(); har1.rekisteroi(); 
   har2 = new Harjoituskerta(); har2.vastaaJuoksu(); har2.rekisteroi(); 
   l11 = new Laji(); l11.vastaaJuoksu(); 
   l12 = new Laji(); l12.vastaaJuoksu(); 
   l21 = new Laji(); l21.vastaaJuoksu(); 
   l22 = new Laji(); l22.vastaaJuoksu(); 
   l23 = new Laji(); l23.vastaaJuoksu(); 
   try {
       treeni.lisaa(har1); 
       treeni.lisaa(har2); 
       treeni.lisaa(l11); 
       treeni.lisaa(l12); 
       treeni.lisaa(l21); 
       treeni.lisaa(l22); 
       treeni.lisaa(l23); 
    } catch ( Exception e) {
        System.err.println(e.getMessage()); 
   }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta59 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta59() throws SailoException {    // Treenipaivakirja: 59
    String tiedNimi = "testitreenit"; 
    File dir = new File(tiedNimi); 
    File ftied = new File(tiedNimi+"/lajit.dat"); 
    File fhtied  = new File(tiedNimi+"/harjoitukset.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    fhtied.delete(); 
    treeni = new Treenipaivakirja(); 
    try {
    treeni.lueTiedostosta(tiedNimi); 
    fail("Treenipaivakirja: 73 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    alustaTreenipaivakirja(); 
    assertEquals("From: Treenipaivakirja line: 75", 5, treeni.getLajit()); 
    assertEquals("From: Treenipaivakirja line: 76", 2, treeni.getHarjoitukset()); 
    treeni.setTiedosto(tiedNimi); 
    treeni.tallenna(); 
    treeni = new Treenipaivakirja(); 
    treeni.lueTiedostosta(tiedNimi); 
    assertEquals("From: Treenipaivakirja line: 81", 5, treeni.getLajit()); 
    assertEquals("From: Treenipaivakirja line: 82", 2, treeni.getHarjoitukset()); 
    dir.delete(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa162 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa162() throws SailoException {    // Treenipaivakirja: 162
    alustaTreenipaivakirja(); 
    assertEquals("From: Treenipaivakirja line: 165", 2, treeni.etsiHarjoitus("*",0).size()); 
    Harjoituskerta har3 = new Harjoituskerta(); 
    treeni.lisaa(har3); 
    assertEquals("From: Treenipaivakirja line: 168", 3, treeni.etsiHarjoitus("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa181 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa181() throws SailoException {    // Treenipaivakirja: 181
    alustaTreenipaivakirja(); 
    assertEquals("From: Treenipaivakirja line: 184", 5, treeni.etsiLaji("*",0).size()); 
    Laji l24 = new Laji(); 
    treeni.lisaa(l24); 
    assertEquals("From: Treenipaivakirja line: 187", 6, treeni.etsiLaji("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista267 
   * @throws Exception when error
   */
  @Test
  public void testPoista267() throws Exception {    // Treenipaivakirja: 267
    alustaTreenipaivakirja(); 
    assertEquals("From: Treenipaivakirja line: 270", 2, treeni.etsiHarjoitus("*",0).size()); 
    assertEquals("From: Treenipaivakirja line: 271", 1, treeni.poista(har1)); 
    assertEquals("From: Treenipaivakirja line: 272", 1, treeni.etsiHarjoitus("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaLaji286 
   * @throws Exception when error
   */
  @Test
  public void testPoistaLaji286() throws Exception {    // Treenipaivakirja: 286
    alustaTreenipaivakirja(); 
    assertEquals("From: Treenipaivakirja line: 289", 5, treeni.etsiLaji("*",0).size()); 
    treeni.poistaLaji(l11); 
    assertEquals("From: Treenipaivakirja line: 291", 4, treeni.etsiLaji("*",0).size()); 
  } // Generated by ComTest END
}