package tarkistus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static tarkistus.PvmTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.09 09:56:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTarkistusTest {



  // Generated by ComTest BEGIN
  /** testKarkausvuosi31 */
  @Test
  public void testKarkausvuosi31() {    // PvmTarkistus: 31
    assertEquals("From: PvmTarkistus line: 32", 0, karkausvuosi(1900));
    assertEquals("From: PvmTarkistus line: 33", 0, karkausvuosi(1900));
    assertEquals("From: PvmTarkistus line: 34", 0, karkausvuosi(1901));
    assertEquals("From: PvmTarkistus line: 35", 1, karkausvuosi(1996));
    assertEquals("From: PvmTarkistus line: 36", 1, karkausvuosi(2000));
    assertEquals("From: PvmTarkistus line: 37", 0, karkausvuosi(2001));
    assertEquals("From: PvmTarkistus line: 38", 1, karkausvuosi(2004));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkista54 */
  @Test
  public void testTarkista54() {    // PvmTarkistus: 54
    StringBuilder sb1 = new StringBuilder("29.2.04"); 
    StringBuilder sb2 = new StringBuilder("29.2.05"); 
    StringBuilder sb3 = new StringBuilder("30.10.21"); 
    StringBuilder sb4 = new StringBuilder("1.12.44"); 
    StringBuilder sb5 = new StringBuilder("29.2.41"); 
    assertEquals("From: PvmTarkistus line: 60", true, tarkista(sb1)); 
    assertEquals("From: PvmTarkistus line: 61", false, tarkista(sb2)); 
    assertEquals("From: PvmTarkistus line: 62", true, tarkista(sb3)); 
    assertEquals("From: PvmTarkistus line: 63", true, tarkista(sb4)); 
    assertEquals("From: PvmTarkistus line: 64", false, tarkista(sb5)); 
  } // Generated by ComTest END
}